language: haskell

notifications:
  hipchat:
    rooms:
      - secure: "a1hPEbI6X3yOcb7RaGLLiMNDNugh9mriNtDQdTy6+CaPGJ3tX8T2QYPnLipG\nm+P55un6ARJK+jCy2ZzuoYMdxbIq3s8ohYq5PA5kGGmeE26SnJ/Gd/5GyWXl\nWYBQSXcEj5F+ZQ1tunW4WFWegj4t9RPXnWunTfsEGLHXhDLACcE="
    on_success: always
    on_failure: always
    on_start: always

env:
 - CABALVER=1.22 GHCVER=7.10.1

before_install:
 - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 - travis_retry sudo apt-get update
 - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - |
   if [ $GHCVER = "head" ] || [ ${GHCVER%.*} = "7.8" ] || [ ${GHCVER%.*} = "7.10" ]; then
     travis_retry sudo apt-get install happy-1.19.4 alex-3.1.3
     export PATH=/opt/alex/3.1.3/bin:/opt/happy/1.19.4/bin:$PATH
   else
     travis_retry sudo apt-get install happy alex
   fi

install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests --enable-benchmarks
